// <auto-generated />
using System;
using Final_VS1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_VS1.Migrations
{
    [DbContext(typeof(LittleFishBeautyContext))]
    partial class LittleFishBeautyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_VS1.Data.AnhSanPham", b =>
                {
                    b.Property<int>("IdAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Anh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnh"));

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    b.Property<string>("LoaiAnh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdAnh")
                        .HasName("PK__AnhSanPh__2A42605DB52A0898");

                    b.HasIndex("IdSanPham");

                    b.ToTable("AnhSanPham", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.ChiTietDonHang", b =>
                {
                    b.Property<int>("IdChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ChiTiet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChiTiet"));

                    b.Property<decimal?>("GiaLucDat")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("IdDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ID_DonHang");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdChiTiet")
                        .HasName("PK__ChiTietD__1EF2F7051D97AD3B");

                    b.HasIndex("IdDonHang");

                    b.HasIndex("IdSanPham");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.DanhMuc", b =>
                {
                    b.Property<int>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DanhMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDanhMuc"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DuongDanSeo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DuongDanSEO");

                    b.Property<int?>("IdDanhMucCha")
                        .HasColumnType("int")
                        .HasColumnName("ID_DanhMucCha");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThuTuHienThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdDanhMuc")
                        .HasName("PK__DanhMuc__662ACB016EEFE420");

                    b.HasIndex("IdDanhMucCha");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.DonHang", b =>
                {
                    b.Property<int>("IdDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DonHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonHang"));

                    b.Property<string>("DiaChiNguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoan");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDonHang")
                        .HasName("PK__DonHang__99B7263948C5D74C");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.SanPham", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanPham"));

                    b.Property<string>("CachSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("IdDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("ID_DanhMuc");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<int?>("SoLuongTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdSanPham")
                        .HasName("PK__SanPham__617EA3925991D7F8");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex(new[] { "Sku" }, "UQ__SanPham__CA1ECF0D06E88054")
                        .IsUnique()
                        .HasFilter("[SKU] IS NOT NULL");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TaiKhoan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTaiKhoan")
                        .HasName("PK__TaiKhoan__0E3EC21024A144EF");

                    b.HasIndex(new[] { "Email" }, "UQ__TaiKhoan__A9D10534BAF084CD")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("Final_VS1.Data.AnhSanPham", b =>
                {
                    b.HasOne("Final_VS1.Data.SanPham", "IdSanPhamNavigation")
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("IdSanPham")
                        .HasConstraintName("FK__AnhSanPha__ID_Sa__47DBAE45");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.ChiTietDonHang", b =>
                {
                    b.HasOne("Final_VS1.Data.DonHang", "IdDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IdDonHang")
                        .HasConstraintName("FK__ChiTietDo__ID_Do__4F7CD00D");

                    b.HasOne("Final_VS1.Data.SanPham", "IdSanPhamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("IdSanPham")
                        .HasConstraintName("FK__ChiTietDo__ID_Sa__5070F446");

                    b.Navigation("IdDonHangNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.DanhMuc", b =>
                {
                    b.HasOne("Final_VS1.Data.DanhMuc", "IdDanhMucChaNavigation")
                        .WithMany("InverseIdDanhMucChaNavigation")
                        .HasForeignKey("IdDanhMucCha")
                        .HasConstraintName("FK__DanhMuc__ID_Danh__3D5E1FD2");

                    b.Navigation("IdDanhMucChaNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.DonHang", b =>
                {
                    b.HasOne("Final_VS1.Data.TaiKhoan", "IdTaiKhoanNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdTaiKhoan")
                        .HasConstraintName("FK__DonHang__ID_TaiK__4BAC3F29");

                    b.Navigation("IdTaiKhoanNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.SanPham", b =>
                {
                    b.HasOne("Final_VS1.Data.DanhMuc", "IdDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDanhMuc")
                        .HasConstraintName("FK__SanPham__ID_Danh__440B1D61");

                    b.Navigation("IdDanhMucNavigation");
                });

            modelBuilder.Entity("Final_VS1.Data.DanhMuc", b =>
                {
                    b.Navigation("InverseIdDanhMucChaNavigation");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Final_VS1.Data.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("Final_VS1.Data.SanPham", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("Final_VS1.Data.TaiKhoan", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
